-- Segurança de linha para o funcionário e validação de ponto no PostgreSQL.
-- Não apaga nem atualiza funcionários ou registros históricos.

BEGIN;

DO $$
BEGIN
  IF to_regclass('public."Funcionarios"') IS NULL THEN
    RAISE EXCEPTION 'A tabela public."Funcionarios" não existe.';
  END IF;
  IF to_regclass('public.pontos') IS NULL THEN
    RAISE EXCEPTION 'A tabela public.pontos não existe.';
  END IF;
END
$$;

CREATE TABLE IF NOT EXISTS public.perfis (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auth_user_id uuid NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  nome text NOT NULL,
  email text NOT NULL,
  tipo text NOT NULL CHECK (tipo = 'diretor'),
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public."Funcionarios"
  ADD COLUMN IF NOT EXISTS auth_user_id uuid;

DO $$
DECLARE
  v_coluna record;
BEGIN
  FOR v_coluna IN
    SELECT *
    FROM (VALUES
      ('Funcionarios', 'id'),
      ('Funcionarios', 'created_at'),
      ('Funcionarios', 'nome'),
      ('Funcionarios', 'funcao'),
      ('Funcionarios', 'auth_user_id'),
      ('pontos', 'id'),
      ('pontos', 'funcionario_id'),
      ('pontos', 'entrada'),
      ('pontos', 'saida'),
      ('perfis', 'id'),
      ('perfis', 'auth_user_id'),
      ('perfis', 'nome'),
      ('perfis', 'email'),
      ('perfis', 'tipo'),
      ('perfis', 'created_at')
    ) AS esperado(tabela, coluna)
  LOOP
    IF NOT EXISTS (
      SELECT 1
      FROM information_schema.columns
      WHERE table_schema = 'public'
        AND table_name = v_coluna.tabela
        AND column_name = v_coluna.coluna
    ) THEN
      RAISE EXCEPTION 'Falta a coluna public.%.%. Nenhum dado foi removido.',
        v_coluna.tabela, v_coluna.coluna;
    END IF;
  END LOOP;

  IF (
    SELECT data_type
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'Funcionarios'
      AND column_name = 'auth_user_id'
  ) <> 'uuid' THEN
    RAISE EXCEPTION 'public."Funcionarios".auth_user_id precisa ser uuid.';
  END IF;
END
$$;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM public.perfis WHERE auth_user_id IS NULL) THEN
    RAISE EXCEPTION 'Há perfis sem auth_user_id. Revise public.perfis antes da migration.';
  END IF;

  ALTER TABLE public.perfis
    ALTER COLUMN auth_user_id SET NOT NULL;
END
$$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM public."Funcionarios"
    WHERE auth_user_id IS NOT NULL
    GROUP BY auth_user_id
    HAVING count(*) > 1
  ) THEN
    RAISE EXCEPTION 'Há auth_user_id duplicados em public."Funcionarios". Revise esses vínculos.';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public."Funcionarios" f
    LEFT JOIN auth.users u ON u.id = f.auth_user_id
    WHERE f.auth_user_id IS NOT NULL
      AND u.id IS NULL
  ) THEN
    RAISE EXCEPTION 'Há auth_user_id em public."Funcionarios" sem usuário correspondente em auth.users.';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint c
    JOIN pg_attribute a
      ON a.attrelid = c.conrelid
     AND a.attnum = ANY (c.conkey)
    WHERE c.contype = 'f'
      AND c.conrelid = 'public."Funcionarios"'::regclass
      AND c.confrelid = 'auth.users'::regclass
      AND a.attname = 'auth_user_id'
  ) THEN
    ALTER TABLE public."Funcionarios"
      ADD CONSTRAINT funcionarios_auth_user_id_fkey
      FOREIGN KEY (auth_user_id)
      REFERENCES auth.users(id)
      ON DELETE SET NULL;
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint c
    JOIN pg_attribute a
      ON a.attrelid = c.conrelid
     AND a.attnum = ANY (c.conkey)
    WHERE c.contype = 'f'
      AND c.conrelid = 'public.perfis'::regclass
      AND c.confrelid = 'auth.users'::regclass
      AND a.attname = 'auth_user_id'
  ) THEN
    ALTER TABLE public.perfis
      ADD CONSTRAINT perfis_auth_user_id_fkey
      FOREIGN KEY (auth_user_id)
      REFERENCES auth.users(id)
      ON DELETE CASCADE;
  END IF;
END
$$;

CREATE UNIQUE INDEX IF NOT EXISTS funcionarios_auth_user_id_unique
  ON public."Funcionarios" (auth_user_id)
  WHERE auth_user_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS perfis_auth_user_id_unique
  ON public.perfis (auth_user_id);

-- Impede duas jornadas abertas simultâneas para a mesma pessoa.
-- Se os dados antigos já tiverem duplicatas abertas, mantém-nos e informa no resultado.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM public.pontos
    WHERE saida IS NULL
    GROUP BY funcionario_id
    HAVING count(*) > 1
  ) THEN
    RAISE WARNING 'Índice de jornada única não foi criado: existem funcionários com mais de um ponto sem saída. Os registros foram preservados.';
  ELSE
    CREATE UNIQUE INDEX IF NOT EXISTS pontos_uma_jornada_aberta_por_funcionario
      ON public.pontos (funcionario_id)
      WHERE saida IS NULL;
  END IF;
END
$$;

ALTER TABLE public."Funcionarios" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pontos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.perfis ENABLE ROW LEVEL SECURITY;

GRANT USAGE ON SCHEMA public TO authenticated, service_role;

REVOKE ALL PRIVILEGES
  ON TABLE public."Funcionarios", public.pontos, public.perfis
  FROM PUBLIC, anon, authenticated;

GRANT SELECT ON TABLE public."Funcionarios" TO authenticated;
GRANT SELECT ON TABLE public.perfis TO authenticated;
GRANT SELECT ON TABLE public.pontos TO authenticated;

-- A gravação de ponto passa pela RPC, que deriva funcionario_id de auth.uid().
GRANT SELECT, INSERT ON TABLE public."Funcionarios" TO service_role;
GRANT SELECT ON TABLE public.pontos, public.perfis TO service_role;

DO $$
DECLARE
  v_sequencia text;
BEGIN
  v_sequencia := pg_get_serial_sequence('public."Funcionarios"', 'id');
  IF v_sequencia IS NOT NULL THEN
    EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO service_role', v_sequencia);
  END IF;
END
$$;

-- Policies permissivas próprias e guards restritivos são aditivos: policies antigas permanecem.
DO $$
DECLARE
  p record;
  existente record;
  v_sql text;
  v_expr text;
BEGIN
  FOR p IN
    SELECT *
    FROM (VALUES
      ('perfis', 'perfis_diretor_select_proprio', 'PERMISSIVE', 'SELECT', '(SELECT auth.uid()) = auth_user_id AND tipo = ''diretor''', NULL::text),
      ('perfis', 'perfis_diretor_select_guard', 'RESTRICTIVE', 'SELECT', '(SELECT auth.uid()) = auth_user_id AND tipo = ''diretor''', NULL::text),
      ('Funcionarios', 'funcionarios_authenticated_select_proprio', 'PERMISSIVE', 'SELECT', 'auth_user_id = (SELECT auth.uid())', NULL::text),
      ('Funcionarios', 'funcionarios_authenticated_select_guard', 'RESTRICTIVE', 'SELECT', 'auth_user_id = (SELECT auth.uid())', NULL::text),
      ('pontos', 'pontos_authenticated_select_proprio', 'PERMISSIVE', 'SELECT', 'EXISTS (SELECT 1 FROM public."Funcionarios" AS f WHERE f.id = pontos.funcionario_id AND f.auth_user_id = (SELECT auth.uid()))', NULL::text),
      ('pontos', 'pontos_authenticated_select_guard', 'RESTRICTIVE', 'SELECT', 'EXISTS (SELECT 1 FROM public."Funcionarios" AS f WHERE f.id = pontos.funcionario_id AND f.auth_user_id = (SELECT auth.uid()))', NULL::text),
      ('pontos', 'pontos_authenticated_insert_proprio', 'PERMISSIVE', 'INSERT', NULL::text, 'EXISTS (SELECT 1 FROM public."Funcionarios" AS f WHERE f.id = pontos.funcionario_id AND f.auth_user_id = (SELECT auth.uid()))'),
      ('pontos', 'pontos_authenticated_insert_guard', 'RESTRICTIVE', 'INSERT', NULL::text, 'EXISTS (SELECT 1 FROM public."Funcionarios" AS f WHERE f.id = pontos.funcionario_id AND f.auth_user_id = (SELECT auth.uid()))'),
      ('pontos', 'pontos_authenticated_update_proprio', 'PERMISSIVE', 'UPDATE', 'EXISTS (SELECT 1 FROM public."Funcionarios" AS f WHERE f.id = pontos.funcionario_id AND f.auth_user_id = (SELECT auth.uid()))', 'EXISTS (SELECT 1 FROM public."Funcionarios" AS f WHERE f.id = pontos.funcionario_id AND f.auth_user_id = (SELECT auth.uid()))'),
      ('pontos', 'pontos_authenticated_update_guard', 'RESTRICTIVE', 'UPDATE', 'EXISTS (SELECT 1 FROM public."Funcionarios" AS f WHERE f.id = pontos.funcionario_id AND f.auth_user_id = (SELECT auth.uid()))', 'EXISTS (SELECT 1 FROM public."Funcionarios" AS f WHERE f.id = pontos.funcionario_id AND f.auth_user_id = (SELECT auth.uid()))')
    ) AS policies(tabela, nome, permissive, comando, usando, check_expr)
  LOOP
    SELECT *
    INTO existente
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = p.tabela
      AND policyname = p.nome;

    IF FOUND THEN
      IF existente.permissive <> p.permissive
        OR existente.cmd <> p.comando
        OR existente.roles::text <> '{authenticated}' THEN
        RAISE EXCEPTION 'A policy public.%.% existe com configuração diferente. Revise-a antes de executar novamente.', p.tabela, p.nome;
      END IF;

      IF p.usando IS NOT NULL THEN
        v_expr := existente.qual;
        IF v_expr IS NULL
          OR v_expr NOT ILIKE '%auth.uid%'
          OR v_expr NOT ILIKE '%auth_user_id%'
          OR v_expr ~* '\mOR\M'
          OR v_expr ~* '(^|[^a-z])true([^a-z]|$)' THEN
          RAISE EXCEPTION 'A expressão da policy public.%.% precisa ser revisada.', p.tabela, p.nome;
        END IF;
        IF p.tabela = 'pontos' AND v_expr NOT ILIKE '%funcionario_id%' THEN
          RAISE EXCEPTION 'A policy public.%.% não valida funcionario_id.', p.tabela, p.nome;
        END IF;
        IF p.tabela = 'perfis' AND v_expr NOT ILIKE '%tipo%' THEN
          RAISE EXCEPTION 'A policy public.%.% não valida tipo diretor.', p.tabela, p.nome;
        END IF;
      END IF;

      IF p.check_expr IS NOT NULL THEN
        v_expr := existente.with_check;
        IF v_expr IS NULL
          OR v_expr NOT ILIKE '%auth.uid%'
          OR v_expr NOT ILIKE '%auth_user_id%'
          OR v_expr NOT ILIKE '%funcionario_id%'
          OR v_expr ~* '\mOR\M'
          OR v_expr ~* '(^|[^a-z])true([^a-z]|$)' THEN
          RAISE EXCEPTION 'A expressão WITH CHECK da policy public.%.% precisa ser revisada.', p.tabela, p.nome;
        END IF;
      END IF;
    ELSE
      v_sql := format(
        'CREATE POLICY %I ON public.%I AS %s FOR %s TO authenticated',
        p.nome, p.tabela, p.permissive, p.comando
      );
      IF p.usando IS NOT NULL THEN
        v_sql := v_sql || format(' USING (%s)', p.usando);
      END IF;
      IF p.check_expr IS NOT NULL THEN
        v_sql := v_sql || format(' WITH CHECK (%s)', p.check_expr);
      END IF;
      EXECUTE v_sql;
    END IF;
  END LOOP;
END
$$;

-- Registra entrada/saída no servidor. funcionario_id vem sempre de auth.uid().
CREATE OR REPLACE FUNCTION public.registrar_ponto(
  p_tipo text,
  p_latitude double precision,
  p_longitude double precision
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_funcionario_id public."Funcionarios".id%TYPE;
  v_registro public.pontos%ROWTYPE;
  v_latitude_residencia CONSTANT double precision := -23.4668757;
  v_longitude_residencia CONSTANT double precision := -46.8714549;
  v_raio_permitido CONSTANT double precision := 50;
  v_a double precision;
  v_distancia double precision;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'SESSAO_NAO_AUTENTICADA' USING ERRCODE = '42501';
  END IF;

  IF p_tipo IS NULL OR p_tipo NOT IN ('Entrada', 'Saída') THEN
    RAISE EXCEPTION 'TIPO_DE_PONTO_INVALIDO' USING ERRCODE = '22023';
  END IF;

  IF p_latitude IS NULL OR p_longitude IS NULL
    OR p_latitude < -90 OR p_latitude > 90
    OR p_longitude < -180 OR p_longitude > 180 THEN
    RAISE EXCEPTION 'LOCALIZACAO_INVALIDA' USING ERRCODE = '22023';
  END IF;

  v_a := pg_catalog.power(pg_catalog.sin(pg_catalog.radians(p_latitude - v_latitude_residencia) / 2), 2)
    + pg_catalog.cos(pg_catalog.radians(v_latitude_residencia))
    * pg_catalog.cos(pg_catalog.radians(p_latitude))
    * pg_catalog.power(pg_catalog.sin(pg_catalog.radians(p_longitude - v_longitude_residencia) / 2), 2);
  v_a := LEAST(1.0, GREATEST(0.0, v_a));
  v_distancia := 2 * 6371000 * pg_catalog.asin(pg_catalog.sqrt(v_a));

  IF v_distancia > v_raio_permitido THEN
    RAISE EXCEPTION 'FORA_DA_AREA' USING ERRCODE = '42501';
  END IF;

  SELECT f.id
  INTO v_funcionario_id
  FROM public."Funcionarios" AS f
  WHERE f.auth_user_id = auth.uid()
  FOR UPDATE;

  IF v_funcionario_id IS NULL THEN
    RAISE EXCEPTION 'FUNCIONARIO_NAO_VINCULADO' USING ERRCODE = '42501';
  END IF;

  IF p_tipo = 'Entrada' THEN
    IF EXISTS (
      SELECT 1
      FROM public.pontos AS p
      WHERE p.funcionario_id = v_funcionario_id
        AND p.saida IS NULL
    ) THEN
      RAISE EXCEPTION 'JORNADA_ABERTA' USING ERRCODE = '23505';
    END IF;

    BEGIN
      INSERT INTO public.pontos (funcionario_id, entrada, saida)
      VALUES (v_funcionario_id, pg_catalog.clock_timestamp(), NULL)
      RETURNING * INTO v_registro;
    EXCEPTION WHEN unique_violation THEN
      RAISE EXCEPTION 'JORNADA_ABERTA' USING ERRCODE = '23505';
    END;
  ELSE
    SELECT p.*
    INTO v_registro
    FROM public.pontos AS p
    WHERE p.funcionario_id = v_funcionario_id
      AND p.saida IS NULL
    ORDER BY p.entrada DESC
    LIMIT 1
    FOR UPDATE;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'SEM_JORNADA_ABERTA' USING ERRCODE = 'P0001';
    END IF;

    UPDATE public.pontos AS p
    SET saida = pg_catalog.clock_timestamp()
    WHERE p.id = v_registro.id
    RETURNING p.* INTO v_registro;
  END IF;

  RETURN pg_catalog.jsonb_build_object(
    'id', v_registro.id,
    'funcionario_id', v_registro.funcionario_id,
    'entrada', v_registro.entrada,
    'saida', v_registro.saida
  );
END;
$$;

REVOKE ALL PRIVILEGES
  ON FUNCTION public.registrar_ponto(text, double precision, double precision)
  FROM PUBLIC, anon, authenticated;

GRANT EXECUTE
  ON FUNCTION public.registrar_ponto(text, double precision, double precision)
  TO authenticated;

NOTIFY pgrst, 'reload schema';

COMMIT;
