-- Perfis do Diretor, vínculo do funcionário com Supabase Auth e bootstrap inicial.
-- A migration é aditiva: não remove nem reescreve funcionários ou registros de ponto.

BEGIN;

CREATE TABLE IF NOT EXISTS public.perfis (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auth_user_id uuid NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  nome text NOT NULL,
  email text NOT NULL,
  tipo text NOT NULL CHECK (tipo = 'diretor'),
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public."Funcionarios"
  ADD COLUMN IF NOT EXISTS auth_user_id uuid;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM public."Funcionarios"
    WHERE auth_user_id IS NOT NULL
    GROUP BY auth_user_id
    HAVING count(*) > 1
  ) THEN
    RAISE EXCEPTION 'Há auth_user_id duplicados em public."Funcionarios". Revise os vínculos antes da migration.';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public."Funcionarios" f
    LEFT JOIN auth.users u ON u.id = f.auth_user_id
    WHERE f.auth_user_id IS NOT NULL
      AND u.id IS NULL
  ) THEN
    RAISE EXCEPTION 'Há auth_user_id em public."Funcionarios" sem usuário correspondente em auth.users.';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint c
    JOIN pg_attribute a
      ON a.attrelid = c.conrelid
     AND a.attnum = ANY (c.conkey)
    WHERE c.contype = 'f'
      AND c.conrelid = 'public."Funcionarios"'::regclass
      AND c.confrelid = 'auth.users'::regclass
      AND a.attname = 'auth_user_id'
  ) THEN
    ALTER TABLE public."Funcionarios"
      ADD CONSTRAINT funcionarios_auth_user_id_fkey
      FOREIGN KEY (auth_user_id)
      REFERENCES auth.users(id)
      ON DELETE SET NULL;
  END IF;
END
$$;

CREATE UNIQUE INDEX IF NOT EXISTS funcionarios_auth_user_id_unique
  ON public."Funcionarios" (auth_user_id)
  WHERE auth_user_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS perfis_auth_user_id_unique
  ON public.perfis (auth_user_id);

ALTER TABLE public.perfis ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public.perfis FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public.perfis TO authenticated;
GRANT SELECT ON TABLE public.perfis TO service_role;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'perfis'
      AND policyname = 'perfis_diretor_select_proprio'
  ) THEN
    EXECUTE $policy$
      CREATE POLICY perfis_diretor_select_proprio
        ON public.perfis
        FOR SELECT
        TO authenticated
        USING ((SELECT auth.uid()) = auth_user_id AND tipo = 'diretor')
    $policy$;
  END IF;
END
$$;

-- Esta RPC só é executável pela Edge Function através de service_role.
-- O lock permite que somente uma chamada concorrente crie o primeiro Diretor.
CREATE OR REPLACE FUNCTION public.bootstrap_director(
  p_auth_user_id uuid,
  p_nome text,
  p_email text
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF p_auth_user_id IS NULL
    OR pg_catalog.btrim(COALESCE(p_nome, '')) = ''
    OR pg_catalog.btrim(COALESCE(p_email, '')) = '' THEN
    RAISE EXCEPTION 'Dados do Diretor inválidos.';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM auth.users u
    WHERE u.id = p_auth_user_id
      AND pg_catalog.lower(u.email::text) = pg_catalog.lower(pg_catalog.btrim(p_email))
      AND u.email_confirmed_at IS NOT NULL
  ) THEN
    RAISE EXCEPTION 'A conta Auth não corresponde ao e-mail confirmado.';
  END IF;

  PERFORM pg_catalog.pg_advisory_xact_lock(8842981);

  IF EXISTS (SELECT 1 FROM public.perfis WHERE tipo = 'diretor') THEN
    RAISE EXCEPTION 'DIRECTOR_ALREADY_EXISTS' USING ERRCODE = '23505';
  END IF;

  INSERT INTO public.perfis (auth_user_id, nome, email, tipo)
  VALUES (
    p_auth_user_id,
    pg_catalog.btrim(p_nome),
    pg_catalog.lower(pg_catalog.btrim(p_email)),
    'diretor'
  );

  INSERT INTO public."Funcionarios" (nome, funcao, auth_user_id)
  VALUES (pg_catalog.btrim(p_nome), 'Proprietário', p_auth_user_id);
END;
$$;

REVOKE ALL PRIVILEGES
  ON FUNCTION public.bootstrap_director(uuid, text, text)
  FROM PUBLIC, anon, authenticated;

GRANT EXECUTE
  ON FUNCTION public.bootstrap_director(uuid, text, text)
  TO service_role;

NOTIFY pgrst, 'reload schema';

COMMIT;
